services:
  catalogue:
    build: ./catalogue
    image: joindevops/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: joindevops/user:1.0.0
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    build: ./cart
    image: joindevops/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  frontend:
    build: ./frontend
    image: joindevops/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
  mongodb:
    build: ./mongodb # it moves to mongodb directory
    image: joindevops/mongodb:1.0.0 # docker build -t joindevops/mongodb:1.0.0
    container_name: mongodb
    volumes:
    - /:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: joindevops/mysql:1.0.0
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually
volumes:
  mongodb: # docker volume create mongodb
  redis:
  mysql:
  rabbitmq: